[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  functions = "netlify/functions"
  publish = ".next"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Schedule the horoscope update function
[[scheduled-functions]]
  name = "update-horoscopes"
  schedule = "@daily"